### ISSUE TITLE
Create home page

### ISSUE THREAD

**Issue by sarasg89** [MohammadKouchaki/Feed-the-foodie#1]
GIVEN I’m a foodie who wants to try new dishes
WHEN I view home page
THEN I’m presented with “cook” and “eat out” options

**Comment by sarasg89** [comment]
Name
Navbar: cook or eat out, about us, contact us
Logo
Short description of how the website works
Buttons to choose options

**Comment by hannazo** [comment]
- [x] Add footer
- [x] Add fonts
- [x] Add logo

**Comment by hannazo** [comment]
- [ ] Update with working links

**Comment by hannazo** [comment]
Home page has been created and added to develop branch

**Comment by hannazo** [comment]
@sarasg89 Hi Sara, can you please take a quick look at the home page. If everything looks good, I'll close this issue.

**Comment by sarasg89** [comment]
> @sarasg89 Hi Sara, can you please take a quick look at the home page. If everything looks good, I'll close this issue.

@hannazo It looks great! But on my screen, the footer is not sticking to the bottom on the page 

<img width="1460" alt="Screenshot 2023-02-06 at 20 00 57" src="https://user-images.githubusercontent.com/118869836/217121368-567a4b54-5403-4842-96da-ff54b592de9e.png">

**Comment by hannazo** [comment]
@sarasg89  I've revised hero section height from fixed to fit the screen. Let me know what you think.

**Comment by hannazo** [comment]
Home page has been completed
