### ISSUE TITLE
Eating out option

### ISSUE THREAD

**Issue by sarasg89** [MohammadKouchaki/Feed-the-foodie#4]
GIVEN a list of cuisines, dishes, type of meal
WHEN I input my location and food selection
THEN I am presented with a list of restaurants 
WHEN I choose a restaurant
THEN a map shows me its location
THEN I see a link for the restaurant's website
WHEN I click on the link
THEN a modal (alert) comes up letting me know I'm about to exit this website

**Comment by hannazo** [comment]
@MohammadKouchaki Hi Mohammad, design of the restaurant page has been completed. You can find html, css and js files in restaurants-html branch. I made some changes to your code:

- Organized type of cuisine in alphabetical order
- Removed vegetarian option as it's not a type of cuisine, rather a dietary restriction/preference.

I've attached a screenshot for your reference. Let me know if you are having issues with adding it to your code. 

![Image](https://user-images.githubusercontent.com/106128732/217330833-8312bf70-f2ac-4ac6-a67c-0e625fa814a4.png)

**Comment by MohammadKouchaki** [comment]
that's great Hanna
