### ISSUE TITLE
Favourites

### ISSUE THREAD

**Issue by sarasg89** [MohammadKouchaki/Feed-the-foodie#8]
GIVEN I have saved a recipe/restaurant to my favourites
WHEN I click on the nav bar link to my favourties
THEN I see various cards with the recipe name and link to the recipe
THEN I see various cards with the name and link to the restaurant
WHEN I don't like recipe/restaurant any more
THEN I can delete the card

**Comment by hannazo** [comment]
@sarasg89 Favourites HTML branch is now up to date. 

- Made some styling changes 
- Added card hover effect
- Added generic text to intro section (feel free to change it)

I've attached a screenshot for your reference.  

![Image](https://user-images.githubusercontent.com/106128732/216881832-0dcdf5f8-e6ff-41fc-a4ba-2bf3c06c9948.png)

**Comment by sarasg89** [comment]
- [x] Display favourite recipes already saved in local storage
- [x] Delete button for recipes
- [x] Display favourite restaurants already saved in local storage
- [x] Delete button for recipes
- [x] Updated page with Hanna's styling

**Comment by sarasg89** [comment]
This page needs to be tested once the issue with the TripAdvisor API / CORS issue is resolved

**Comment by sarasg89** [comment]
This page is now completed
